# Generated by Django 3.0.6 on 2020-05-18 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0002_auto_20200517_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='resource_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_management.ResourcePosition'),
        ),
        migrations.AlterField(
            model_name='resourceposition',
            name='medical_qualification',
            field=models.IntegerField(choices=[(0, 'Ersthelfer'), (1, 'Schulsanitäter'), (2, 'Sanitätshelfer'), (3, 'Rettungshelfer'), (4, 'Rettungssanitäter'), (5, 'Rettungsassistent'), (6, 'Notfallsanitäter'), (7, 'Notarzt')]),
        ),
    ]
