# Generated by Django 3.0.6 on 2020-05-18 17:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0003_auto_20200518_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='meeting_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 17, 40, 43, 545523, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
