# Generated by Django 3.0.6 on 2020-05-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='medical_qualification',
            field=models.IntegerField(blank=True, choices=[(0, 'Ersthelfer'), (1, 'Schulsanitäter'), (2, 'Sanitätshelfer'), (3, 'Rettungshelfer'), (4, 'Rettungssanitäter'), (5, 'Rettungsassistent'), (6, 'Notfallsanitäter'), (7, 'Notarzt')], null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='qualifications',
            field=models.ManyToManyField(blank=True, to='user_management.Qualification'),
        ),
    ]
