# Generated by Django 3.0.6 on 2020-08-18 21:05
from datetime import datetime

from django.contrib.auth.hashers import make_password
from django.db import migrations
from django.utils.translation import gettext as _


# This does not use historical models, but the current version of Group and Permission
# It might break if these models change in the future, which will only happen
# * on Django Version upgrade
# * when we introduce custom models


def create_initial_objects(apps, schema_editor):
    UserProfile = apps.get_model("user_management", "UserProfile")
    user = UserProfile(
        email="admin@localhost",
        first_name="Admin",
        last_name="Localhost",
        date_of_birth=datetime(year=1970, month=1, day=1),
    )
    user.is_staff = True
    user.is_superuser = True
    user.password = make_password("admin")
    user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0002_initial_permissions"),
    ]

    operations = [
        migrations.RunPython(create_initial_objects),
    ]
