# Generated by Django 3.0.6 on 2020-08-18 21:05
from datetime import datetime

from django.contrib.auth.hashers import make_password
from django.db import migrations


# This does not use historical models, but the current version of Group and Permission
# It might break if these models change in the future, which will only happen
# * on Django Version upgrade
# * when we introduce custom models


def create_initial_objects(apps, schema_editor):
    from django.contrib.auth.models import Group
    from user_management.models import UserProfile
    from guardian.shortcuts import assign_perm

    user = UserProfile(
        email="admin@localhost",
        first_name="Admin",
        last_name="Localhost",
        date_of_birth=datetime(year=1970, month=1, day=1),
    )

    user.is_staff = True
    user.is_superuser = True
    user.password = make_password("admin")
    user.save()

    helfer = Group.objects.create(name="Helfer")
    helfer.user_set.add(user)
    helfer.save()
    assign_perm("publish_event_for_group", helfer, helfer)


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0002_initial_permissions"),
    ]

    operations = [
        migrations.RunPython(create_initial_objects, migrations.RunPython.noop),
    ]
