# Generated by Django 4.1.7 on 2023-06-07 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_userprofile_date_of_birth"),
        ("federation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FederatedEventShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.event"),
                ),
                ("shared_with", models.ManyToManyField(to="federation.federatedguest")),
            ],
        ),
    ]
