# Generated by Django 4.1.7 on 2023-08-04 16:02

import secrets

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL),
        ("federation", "0002_federatedeventshare"),
    ]

    operations = [
        migrations.AlterField(
            model_name="federatedguest",
            name="access_token",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="federatedguest",
            name="url",
            field=models.URLField(verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="federatedhost",
            name="oauth_application",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="federatedhost",
            name="url",
            field=models.URLField(verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="invitecode",
            name="code",
            field=models.CharField(default=secrets.token_hex, max_length=255),
        ),
        migrations.AlterField(
            model_name="invitecode",
            name="url",
            field=models.URLField(verbose_name="URL"),
        ),
    ]
