# Generated by Django 5.0.11 on 2025-05-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("federation", "0005_alter_federatedeventshare_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="federateduser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="date of birth"),
        ),
    ]
