---
uberspace_instances:
  hosts:
    ephios_staging:
      ansible_user: staghios
      ansible_host: despina.uberspace.de
      domain: staging.ephios.de
      smtp_mailbox: noreply
      admin_email: Ephios Admins <admin@ephios.de>
      plugins:
        - git+https://github.com/ephios-dev/ephios-testplugin
