# Generated by Django 5.2.4 on 2025-08-01 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0038_eventtype_default_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the question is used to identify the question, for example when picking questions for a shift",
                        max_length=50,
                        verbose_name="Name",
                    ),
                ),
                ("question_text", models.CharField(max_length=250, verbose_name="Question")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "required",
                    models.BooleanField(
                        help_text="Whether users must submit an answer to this question",
                        verbose_name="Required",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Text input"),
                            ("single", "Single choice"),
                            ("multiple", "Multiple choice"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("choices", models.JSONField(default=list, verbose_name="Choices")),
                (
                    "archived",
                    models.BooleanField(
                        default=False,
                        help_text="Archive a question to hide it in the question selection for new shifts without affecting shifts where this question is already in use",
                        verbose_name="Archived",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("answer", models.JSONField(verbose_name="Answer")),
                (
                    "participation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.abstractparticipation"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="questionnaires.question"
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer",
                "verbose_name_plural": "Answers",
            },
        ),
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("questions", models.ManyToManyField(blank=True, to="questionnaires.question")),
                (
                    "shift",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.shift"
                    ),
                ),
            ],
            options={
                "verbose_name": "Questionnaire",
                "verbose_name_plural": "Questionnaires",
            },
        ),
        migrations.CreateModel(
            name="SavedAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("answer", models.JSONField(verbose_name="Answer")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="questionnaires.question"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved answer",
                "verbose_name_plural": "Saved answers",
            },
        ),
    ]
