# Generated by Django 5.2.5 on 2025-08-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaires", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="use_saved_answers",
            field=models.BooleanField(
                default=False,
                help_text="If checked, forms will be prefilled with a users saved answer to this question, if available. Enable this for answers that don't depend on the event it is used in.",
                verbose_name="Use saved answers",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="archived",
            field=models.BooleanField(
                default=False,
                help_text="Archive a question to hide it in the question selection for new shifts without affecting shifts where this question is already in use.",
                verbose_name="Archived",
            ),
        ),
    ]
