# Generated by Django 5.2.10 on 2026-01-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaires", "0002_question_use_saved_answers_alter_question_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="use_saved_answers",
            field=models.BooleanField(
                default=False,
                help_text="If checked, forms will be prefilled with a users saved answer to this question, if available. Enable this if answers are independent of the event the question is used for.",
                verbose_name="Use saved answers",
            ),
        ),
    ]
