# Generated by Django 4.2.4 on 2023-08-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modellogging", "0004_alter_logentry_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="datetime",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
