# Generated by Django 4.1.5 on 2023-01-11 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simpleresource", "0002_resourcecategory_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="simpleresource.resourcecategory",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="resourceallocation",
            name="resources",
            field=models.ManyToManyField(
                blank=True, to="simpleresource.resource", verbose_name="Resources"
            ),
        ),
        migrations.AlterField(
            model_name="resourcecategory",
            name="icon",
            field=models.CharField(default="box", help_text="FontAwesome icon name", max_length=50),
        ),
        migrations.AlterField(
            model_name="resourcecategory",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
    ]
