# Generated by Django 4.1.5 on 2023-01-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simpleresource", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcecategory",
            name="icon",
            field=models.CharField(default="box", max_length=50),
        ),
    ]
