# Generated by Django 4.2.4 on 2023-08-03 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "simpleresource",
            "0003_alter_resource_category_alter_resource_title_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resource",
            options={"verbose_name": "Resource", "verbose_name_plural": "Resources"},
        ),
        migrations.AlterModelOptions(
            name="resourceallocation",
            options={
                "verbose_name": "Resource allocation",
                "verbose_name_plural": "Resource allocations",
            },
        ),
        migrations.AlterModelOptions(
            name="resourcecategory",
            options={
                "verbose_name": "Resource category",
                "verbose_name_plural": "Resource categories",
            },
        ),
    ]
