# Generated by Django 5.0.14 on 2025-05-07 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_participationcomment"),
        ("simpleresource", "0004_alter_resource_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourceallocation",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.shift", verbose_name="Shift"
            ),
        ),
        migrations.AlterField(
            model_name="resourcecategory",
            name="icon",
            field=models.CharField(
                default="box", help_text="FontAwesome icon name", max_length=50, verbose_name="Icon"
            ),
        ),
    ]
