# Generated by Django 4.2.4 on 2023-08-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_alter_page_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={"verbose_name": "Page", "verbose_name_plural": "Pages"},
        ),
        migrations.AlterField(
            model_name="page",
            name="content",
            field=models.TextField(blank=True, verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="page",
            name="publicly_visible",
            field=models.BooleanField(default=False, verbose_name="Publicly visible"),
        ),
        migrations.AlterField(
            model_name="page",
            name="show_in_footer",
            field=models.BooleanField(default=False, verbose_name="Show in footer"),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(
                help_text="The slug is used to generate the page's URL.",
                max_length=250,
                unique=True,
                verbose_name="URL slug",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="title",
            field=models.CharField(max_length=250, verbose_name="Title"),
        ),
    ]
