# Generated by Django 3.1.5 on 2021-03-05 22:41

import secrets

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20210305_1855"),
        ("guests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestuser",
            name="access_token",
            field=models.CharField(default=secrets.token_urlsafe, max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name="EventGuestLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "token",
                    models.CharField(default=secrets.token_urlsafe, max_length=254, unique=True),
                ),
                ("active", models.BooleanField(default=False)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_link",
                        to="core.event",
                    ),
                ),
            ],
        ),
    ]
