# Generated by Django 3.1.5 on 2021-03-05 23:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0003_auto_20210305_2345"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
