# Generated by Django 3.1.5 on 2021-03-05 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20210305_1855"),
        ("guests", "0004_guestuser_created_at"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="guestuser",
            unique_together={("event", "email", "first_name")},
        ),
    ]
