services:
  ephios:
    build: ../../
    restart: unless-stopped
    environment:
      - EMAIL_URL=consolemail://
    env_file:
      - ephios-docker-defaults.env
    ports:
      - 8000:80
    volumes:
      - ephios_django_data:/var/ephios/data/

  ephios_postgres:
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_DB: ephios
      POSTGRES_USER: ephios
      POSTGRES_PASSWORD: ephios
    volumes:
      - ephios_postgres_data:/var/lib/postgresql/data

  ephios_nginx:
    image: nginx:1.19
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ephios_django_data:/var/ephios/data/
    depends_on:
      - ephios

volumes:
  ephios_django_data: { }
  ephios_postgres_data: { }
