# Generated by Django 5.2.10 on 2026-01-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_accesstoken_token_checksum_refreshtoken_token_family_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="authorization_grant_type",
            field=models.CharField(
                choices=[
                    ("authorization-code", "Authorization code"),
                    ("urn:ietf:params:oauth:grant-type:device_code", "Device Code"),
                    ("implicit", "Implicit"),
                    ("password", "Resource owner password-based"),
                    ("client-credentials", "Client credentials"),
                    ("openid-hybrid", "OpenID connect hybrid"),
                ],
                max_length=44,
            ),
        ),
    ]
