# Generated by Django 5.2.13 on 2026-07-08 14:59

import oauth2_provider.generators
import oauth2_provider.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_application_authorization_grant_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="client_secret",
            field=oauth2_provider.models.ClientSecretField(
                blank=True,
                db_index=True,
                default=oauth2_provider.generators.generate_client_secret,
                help_text="Client secret for authentication",
                max_length=255,
            ),
        ),
    ]
