# Generated by Django 5.2.17 on 2026-10-08 19:34

import django.db.models.deletion
import oauth2_provider.generators
import oauth2_provider.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_application_client_secret"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="refreshtoken",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="accesstoken",
            name="resource",
            field=oauth2_provider.models.ResourceJSONField(
                blank=True, default=list, verbose_name="resource"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="cimd_expires_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="When the cached Client ID Metadata Document should be re-fetched",
                null=True,
                verbose_name="CIMD expires at",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="registration_source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("dcr", "Dynamic Client Registration"),
                    ("cimd", "Client ID Metadata Document"),
                ],
                default="manual",
                help_text="How this application was registered (manual, DCR per RFC 7591, or CIMD)",
                max_length=32,
                verbose_name="registration source",
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="resource",
            field=oauth2_provider.models.ResourceJSONField(
                blank=True, default=list, verbose_name="resource"
            ),
        ),
        migrations.AddField(
            model_name="refreshtoken",
            name="resource",
            field=oauth2_provider.models.ResourceJSONField(
                blank=True, default=list, verbose_name="resource"
            ),
        ),
        migrations.AddField(
            model_name="refreshtoken",
            name="token_checksum",
            field=oauth2_provider.models.TokenChecksumField(
                default="dummy", max_length=64, verbose_name="token checksum"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="accesstoken",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
                verbose_name="application",
            ),
        ),
        migrations.AlterField(
            model_name="accesstoken",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="accesstoken",
            name="id_token",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_token",
                to=settings.OAUTH2_PROVIDER_ID_TOKEN_MODEL,
                verbose_name="ID token",
            ),
        ),
        migrations.AlterField(
            model_name="accesstoken",
            name="scope",
            field=models.TextField(blank=True, verbose_name="scope"),
        ),
        migrations.AlterField(
            model_name="accesstoken",
            name="source_refresh_token",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refreshed_access_token",
                to=settings.OAUTH2_PROVIDER_REFRESH_TOKEN_MODEL,
                verbose_name="source refresh token",
            ),
        ),
        migrations.AlterField(
            model_name="accesstoken",
            name="token",
            field=models.TextField(verbose_name="token"),
        ),
        migrations.AlterField(
            model_name="accesstoken",
            name="token_checksum",
            field=oauth2_provider.models.TokenChecksumField(
                db_index=True, max_length=64, unique=True, verbose_name="token checksum"
            ),
        ),
        migrations.AlterField(
            model_name="accesstoken",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
        migrations.AlterField(
            model_name="accesstoken",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="algorithm",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No OIDC support"),
                    ("RS256", "RSA with SHA-2 256"),
                    ("HS256", "HMAC with SHA-2 256"),
                ],
                default="",
                max_length=5,
                verbose_name="algorithm",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="allowed_origins",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Allowed origins list to enable CORS, space separated",
                verbose_name="allowed origins",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="authorization_grant_type",
            field=models.CharField(
                choices=[
                    ("authorization-code", "Authorization code"),
                    ("urn:ietf:params:oauth:grant-type:device_code", "Device Code"),
                    ("implicit", "Implicit"),
                    ("password", "Resource owner password-based"),
                    ("client-credentials", "Client credentials"),
                    ("openid-hybrid", "OpenID connect hybrid"),
                ],
                max_length=44,
                verbose_name="authorization grant type",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="client_id",
            field=models.CharField(
                db_index=True,
                default=oauth2_provider.generators.generate_client_id,
                max_length=255,
                unique=True,
                verbose_name="client ID",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="client_secret",
            field=oauth2_provider.models.ClientSecretField(
                blank=True,
                db_index=True,
                default=oauth2_provider.generators.generate_client_secret,
                help_text="Client secret for authentication",
                max_length=255,
                verbose_name="client secret",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="client_type",
            field=models.CharField(
                choices=[("confidential", "Confidential"), ("public", "Public")],
                max_length=32,
                verbose_name="client type",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="application",
            name="hash_client_secret",
            field=models.BooleanField(default=True, verbose_name="hash client secret"),
        ),
        migrations.AlterField(
            model_name="application",
            name="name",
            field=models.CharField(blank=True, max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="application",
            name="post_logout_redirect_uris",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Allowed Post Logout URIs list, space separated",
                verbose_name="post logout redirect URIs",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="redirect_uris",
            field=models.TextField(
                blank=True,
                help_text="Allowed URIs list, space separated",
                verbose_name="redirect URIs",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="skip_authorization",
            field=models.BooleanField(default=False, verbose_name="skip authorization"),
        ),
        migrations.AlterField(
            model_name="application",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
        migrations.AlterField(
            model_name="application",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
                verbose_name="application",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="claims",
            field=models.TextField(blank=True, verbose_name="claims"),
        ),
        migrations.AlterField(
            model_name="grant",
            name="code",
            field=models.CharField(max_length=255, unique=True, verbose_name="code"),
        ),
        migrations.AlterField(
            model_name="grant",
            name="code_challenge",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="code challenge"
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="code_challenge_method",
            field=models.CharField(
                blank=True,
                choices=[("plain", "plain"), ("S256", "S256")],
                default="",
                max_length=10,
                verbose_name="code challenge method",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="grant",
            name="expires",
            field=models.DateTimeField(verbose_name="expires"),
        ),
        migrations.AlterField(
            model_name="grant",
            name="nonce",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="nonce"),
        ),
        migrations.AlterField(
            model_name="grant",
            name="redirect_uri",
            field=models.TextField(verbose_name="redirect URI"),
        ),
        migrations.AlterField(
            model_name="grant",
            name="scope",
            field=models.TextField(blank=True, verbose_name="scope"),
        ),
        migrations.AlterField(
            model_name="grant",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
        migrations.AlterField(
            model_name="grant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="idtoken",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
                verbose_name="application",
            ),
        ),
        migrations.AlterField(
            model_name="idtoken",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="idtoken",
            name="expires",
            field=models.DateTimeField(verbose_name="expires"),
        ),
        migrations.AlterField(
            model_name="idtoken",
            name="scope",
            field=models.TextField(blank=True, verbose_name="scope"),
        ),
        migrations.AlterField(
            model_name="idtoken",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
        migrations.AlterField(
            model_name="idtoken",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="refreshtoken",
            name="access_token",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refresh_token",
                to=settings.OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL,
                verbose_name="access token",
            ),
        ),
        migrations.AlterField(
            model_name="refreshtoken",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
                verbose_name="application",
            ),
        ),
        migrations.AlterField(
            model_name="refreshtoken",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="refreshtoken",
            name="revoked",
            field=models.DateTimeField(null=True, verbose_name="revoked"),
        ),
        migrations.AlterField(
            model_name="refreshtoken",
            name="token",
            field=models.TextField(verbose_name="token"),
        ),
        migrations.AlterField(
            model_name="refreshtoken",
            name="token_family",
            field=models.UUIDField(
                blank=True, editable=False, null=True, verbose_name="token family"
            ),
        ),
        migrations.AlterField(
            model_name="refreshtoken",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
        migrations.AlterField(
            model_name="refreshtoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="refreshtoken",
            unique_together={("token_checksum", "revoked")},
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(fields=["token_family"], name="api_refresh_token_f_926903_idx"),
        ),
    ]
