# Generated by Django 5.0.3 on 2024-10-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("federation", "0004_remove_federateduser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="federatedeventshare",
            options={
                "verbose_name": "federated event share",
                "verbose_name_plural": "federated event shares",
            },
        ),
        migrations.AlterModelOptions(
            name="federatedguest",
            options={"verbose_name": "federated guest", "verbose_name_plural": "federated guests"},
        ),
        migrations.AlterModelOptions(
            name="federatedhost",
            options={"verbose_name": "federated host", "verbose_name_plural": "federated hosts"},
        ),
        migrations.AlterModelOptions(
            name="federatedparticipation",
            options={
                "verbose_name": "federated participation",
                "verbose_name_plural": "federated participations",
            },
        ),
        migrations.AlterModelOptions(
            name="federateduser",
            options={"verbose_name": "federated user", "verbose_name_plural": "federated users"},
        ),
        migrations.AlterModelOptions(
            name="invitecode",
            options={"verbose_name": "invite code", "verbose_name_plural": "invite codes"},
        ),
    ]
