# Generated by Django 5.2.3 on 2025-07-25 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_abstractconsequence_alter_shift_label_and_more"),
        ("federation", "0006_alter_federateduser_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="federateduser",
            name="federated_instance_identifier",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="FederatedConsequence",
            fields=[
                (
                    "abstractconsequence_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.abstractconsequence",
                    ),
                ),
                (
                    "federated_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="federation.federateduser"
                    ),
                ),
            ],
            options={
                "verbose_name": "Federated consequence",
                "verbose_name_plural": "Federated consequences",
                "db_table": "federatedconsequence",
            },
            bases=("core.abstractconsequence",),
        ),
    ]
