# Generated by Django 5.0.14 on 2025-05-14 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"verbose_name": "Document", "verbose_name_plural": "Documents"},
        ),
    ]
