# Generated by Django 5.0.8 on 2024-09-23 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0029_alter_userprofile_date_of_birth"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/",
                        validators=[django.core.validators.FileExtensionValidator(["pdf"])],
                    ),
                ),
                ("attached_to", models.ManyToManyField(related_name="documents", to="core.event")),
            ],
        ),
    ]
