# Generated by Django 5.0.8 on 2024-10-21 21:43

import django.db.models.deletion
from django.db import migrations, models

import ephios.plugins.files.models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "expiration",
                    models.DateTimeField(default=ephios.plugins.files.models._token_expiration),
                ),
                (
                    "token",
                    models.CharField(
                        default=ephios.plugins.files.models._generate_token,
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="files.document"
                    ),
                ),
            ],
        ),
    ]
