# Generated by Django 3.1.6 on 2021-02-07 23:20

from django.db import migrations


def migrate_content_type(apps, schema_editor):
    from django.contrib.contenttypes.models import ContentType

    for obj in ContentType.objects.filter(app_label="event_management"):
        ContentType.objects.filter(app_label="core", model=obj.model).delete()
        obj.app_label = "core"
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_squashed_event_management_0007_auto_20210207_1309"),
    ]

    operations = [
        migrations.RunPython(migrate_content_type),
    ]
