# Generated by Django 4.2.3 on 2023-08-06 23:21

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_alter_consequence_options_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="userprofile",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="user_email_ci_uniqueness",
                violation_error_message="User profile with this email address already exists.",
            ),
        ),
    ]
