# Generated by Django 5.0.9 on 2024-11-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_identityprovider_internal_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualificationgrant",
            name="externally_managed",
            field=models.BooleanField(
                default=False,
                help_text="The qualification was granted by an external system.",
                verbose_name="externally managed",
            ),
        ),
        migrations.AlterField(
            model_name="identityprovider",
            name="internal_name",
            field=models.CharField(
                help_text="Internal name for this provider.",
                max_length=255,
                unique=True,
                verbose_name="internal name",
                null=False,
            ),
        ),
        migrations.AlterField(
            model_name="identityprovider",
            name="qualification_claim",
            field=models.CharField(
                blank=True,
                help_text="The name of the claim that contains the user's qualifications. Leave empty if your provider does not support this. You can use dot notation to access nested claims. Granted qualifications not found in the claim will be removed from the user on login.",
                max_length=254,
                verbose_name="qualification claim",
            ),
        ),
    ]
