# Generated by Django 5.0.9 on 2025-01-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_shift_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtype",
            name="show_participant_data",
            field=models.SmallIntegerField(
                choices=[
                    (0, "to everyone"),
                    (1, "to confirmed participants"),
                    (2, "only to responsible users"),
                ],
                default=0,
                help_text="If you restrict who can see participant data, others will only be able to see that there is a participation, but not from whom.",
                verbose_name="show participant data",
            ),
        ),
    ]
