# Generated by Django 5.0.10 on 2025-02-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_eventtype_show_participant_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventtype",
            name="show_participant_data",
            field=models.SmallIntegerField(
                choices=[
                    (0, "to logged in users"),
                    (1, "to confirmed participants"),
                    (2, "only to responsible users"),
                    (3, "to everyone including guests and federated users"),
                ],
                default=0,
                help_text="If you restrict who can see participant data, others will only be able to see that there is a participation, but not from whom.",
                verbose_name="show participant data",
            ),
        ),
    ]
