# Generated by Django 5.0.14 on 2025-05-14 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_participationcomment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="identityprovider",
            options={
                "verbose_name": "Identity provider",
                "verbose_name_plural": "Identity providers",
            },
        ),
    ]
