# Generated by Django 5.0.14 on 2025-05-21 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_alter_identityprovider_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participationcomment",
            options={
                "ordering": ("created_at",),
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.AlterField(
            model_name="participationcomment",
            name="authored_by_responsible",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsible user",
            ),
        ),
        migrations.AlterField(
            model_name="participationcomment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="participationcomment",
            name="participation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="core.abstractparticipation",
                verbose_name="Participation",
            ),
        ),
    ]
