# Generated by Django 5.2.1 on 2025-05-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_alter_participationcomment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtype",
            name="default_description",
            field=models.TextField(
                blank=True,
                help_text="New events of this type will start out with this description.",
                null=True,
                verbose_name="default description",
            ),
        ),
    ]
