# Generated by Django 5.2.13 on 2026-04-20 19:46

from django.db import migrations, models

import ephios.extra.json


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_eventtype_default_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="disabled_notifications",
            field=models.JSONField(
                blank=True,
                decoder=ephios.extra.json.CustomJSONDecoder,
                default=list,
                encoder=ephios.extra.json.CustomJSONEncoder,
            ),
        ),
    ]
