# Generated by Django 5.2.12 on 2026-04-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_alter_userprofile_disabled_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="planner_note",
            field=models.TextField(
                blank=True,
                help_text="Note only visible to responsibles of this event.",
                null=True,
                verbose_name="planner note",
            ),
        ),
    ]
