# Generated by Django 4.2.4 on 2023-09-19 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0021_alter_qualificationcategory_show_with_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockComposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("optional", models.BooleanField(default=False, verbose_name="optional")),
            ],
        ),
        migrations.CreateModel(
            name="BuildingBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "block_type",
                    models.CharField(
                        choices=[("atomic", "Atomic"), ("composite", "Composite")],
                        max_length=64,
                        verbose_name="Type",
                    ),
                ),
                (
                    "allow_more",
                    models.BooleanField(
                        default=False,
                        help_text="Allow more participants that qualify for any of the positions.",
                        verbose_name="allow more",
                    ),
                ),
                (
                    "sub_blocks",
                    models.ManyToManyField(
                        through="complexsignup.BlockComposition", to="complexsignup.buildingblock"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=255, verbose_name="Label")),
                ("optional", models.BooleanField(default=False, verbose_name="optional")),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="complexsignup.buildingblock",
                    ),
                ),
                (
                    "qualifications",
                    models.ManyToManyField(
                        blank=True, to="core.qualification", verbose_name="required qualifications"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlockQualificationRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("everyone", models.BooleanField()),
                ("at_least", models.PositiveSmallIntegerField(default=0)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualification_requirements",
                        to="complexsignup.buildingblock",
                    ),
                ),
                ("qualifications", models.ManyToManyField(to="core.qualification")),
            ],
        ),
        migrations.AddField(
            model_name="blockcomposition",
            name="composite_block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="super_compositions",
                to="complexsignup.buildingblock",
            ),
        ),
        migrations.AddField(
            model_name="blockcomposition",
            name="sub_block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_compositions",
                to="complexsignup.buildingblock",
            ),
        ),
    ]
