# Generated by Django 4.2.4 on 2023-09-21 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("complexsignup", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="buildingblock",
            old_name="uuid",
            new_name="id",
        ),
    ]
