# Generated by Django 5.0.8 on 2024-09-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complexsignup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockcomposition",
            name="label",
            field=models.CharField(blank=True, max_length=255, verbose_name="Label"),
        ),
    ]
