# Generated by Django 4.2.4 on 2023-09-20 09:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("complexsignup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildingblock",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name="UUID"),
        ),
    ]
