# Generated by Django 5.2.4 on 2025-07-17 10:10

from django.db import migrations

from ephios.plugins.complexsignup.structure import ComplexShiftStructure


def adjust_multiblock(apps, schema_editor):
    """
    Change from e.g.
    {"building_block": 8, "choose_preferred_unit": true}
    to
    {"minimum_age": null, "choose_preferred_unit": true, "starting_blocks": [{"building_block": 8, "title": "", "optional": false}]}
    """
    Shift = apps.get_model("core", "Shift")
    for shift in Shift.objects.filter(structure_slug=ComplexShiftStructure.slug):
        old_data = shift.structure_configuration
        if "starting_blocks" in old_data:
            continue  # already converted
        new_data = {
            "choose_preferred_unit": old_data["choose_preferred_unit"],
            "minimum_age": None,
            "starting_blocks": [
                {"building_block": old_data["building_block"], "title": "", "optional": False},
            ],
        }
        shift.structure_configuration = new_data
        shift.save()
        for participation in shift.participations.all():
            for field_name in ["dispatched_unit_path", "preferred_unit_path"]:
                # adjust dispatched/preferred unit path
                old_path = participation.structure_data.get(field_name)
                if not old_path or len(old_path) < 5:
                    continue
                # we inserted an index number for multiple starting blocks
                # a number that was root-16-18 should now be root-0-16-18
                # so we simply replace "root" with "root-0"
                new_path = f"root-0{old_path[4:]}"
                participation.structure_data[field_name] = new_path
            participation.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_eventtype_default_description"),
        ("complexsignup", "0003_alter_buildingblock_sub_blocks"),
    ]

    operations = [
        migrations.RunPython(adjust_multiblock),
    ]
