# Generated by Django 4.2.7 on 2023-11-11 15:13

from django.db import migrations


def migrate_instant_and_requestconfirm_to_simple_qualification_required(apps, schema_editor):
    Shift = apps.get_model("core", "Shift")
    for shift in Shift.objects.all():
        if shift.signup_method_slug == "instant_confirmation":
            shift.signup_method_slug = "simple_qualification_required"
            shift.signup_configuration["instant_confirmation"] = True
            shift.save()
        if shift.signup_method_slug == "request_confirm":
            shift.signup_method_slug = "simple_qualification_required"
            shift.signup_configuration["instant_confirmation"] = False
            shift.save()


def revert_migration(apps, schema_editor):
    Shift = apps.get_model("core", "Shift")
    for shift in Shift.objects.all():
        if shift.signup_method_slug == "simple_qualification_required":
            if shift.signup_configuration["instant_confirmation"]:
                shift.signup_method_slug = "instant_confirmation"
            else:
                shift.signup_method_slug = "request_confirm"
            shift.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_remove_userprofile_first_name_and_more"),
    ]

    operations = [
        migrations.RunPython(
            migrate_instant_and_requestconfirm_to_simple_qualification_required,
            revert_migration,
        ),
    ]
