# Generated by Django 3.2.7 on 2021-10-03 15:34

from django.db import migrations, models

import ephios.core.models.users


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_rename_included_qualifications_qualification_includes"),
    ]

    operations = [
        migrations.AddField(
            model_name="abstractparticipation",
            name="individual_end_time",
            field=models.DateTimeField(null=True, verbose_name="end time"),
        ),
        migrations.AddField(
            model_name="abstractparticipation",
            name="individual_start_time",
            field=models.DateTimeField(null=True, verbose_name="start time"),
        ),
        migrations.AlterField(
            model_name="qualificationgrant",
            name="expires",
            field=ephios.core.models.users.ExpirationDateField(
                blank=True, null=True, verbose_name="expiration date"
            ),
        ),
    ]
