# Generated by Django 3.2.8 on 2021-10-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_auto_20211027_2203"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventtype",
            name="can_grant_qualification",
        ),
        migrations.AddField(
            model_name="abstractparticipation",
            name="comment",
            field=models.CharField(blank=True, max_length=255, verbose_name="Comment"),
        ),
        migrations.AddField(
            model_name="abstractparticipation",
            name="individual_end_time",
            field=models.DateTimeField(null=True, verbose_name="individual end time"),
        ),
        migrations.AddField(
            model_name="abstractparticipation",
            name="individual_start_time",
            field=models.DateTimeField(null=True, verbose_name="individual start time"),
        ),
        migrations.AlterField(
            model_name="abstractparticipation",
            name="state",
            field=models.IntegerField(
                choices=[
                    (0, "requested"),
                    (1, "confirmed"),
                    (2, "declined by user"),
                    (3, "rejected by responsible"),
                    (4, "getting dispatched"),
                ],
                default=4,
                verbose_name="state",
            ),
        ),
    ]
