# Generated by Django 3.2.7 on 2021-10-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_auto_20211003_1734"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventtype",
            name="can_grant_qualification",
        ),
    ]
