# Generated by Django 3.2.10 on 2021-12-18 11:46

from django.db import migrations, models

import ephios.core.models.events


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_auto_20211106_1852"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="failed",
        ),
        migrations.AddField(
            model_name="notification",
            name="backends_tried",
            field=models.JSONField(
                default=list,
                help_text="list of notification backend slugs for which sending the notification was tried",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="errors",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="abstractparticipation",
            name="shift",
            field=models.ForeignKey(
                on_delete=ephios.core.models.events.NON_POLYMORPHIC_CASCADE,
                related_name="participations",
                to="core.shift",
                verbose_name="shift",
            ),
        ),
    ]
