# Generated by Django 3.2.7 on 2021-10-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_remove_eventtype_can_grant_qualification"),
    ]

    operations = [
        migrations.AddField(
            model_name="abstractparticipation",
            name="comment",
            field=models.CharField(blank=True, max_length=255, verbose_name="Comment"),
        ),
    ]
