# Generated by Django 4.1.6 on 2023-02-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_event_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True, max_length=254, null=True, verbose_name="phone number"
            ),
        ),
    ]
