# Generated by Django 4.1.7 on 2023-03-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_userprofile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(null=True, verbose_name="date of birth"),
        ),
    ]
