# Generated by Django 4.2.4 on 2023-08-03 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_userprofile_date_of_birth"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consequence",
            options={
                "verbose_name": "Consequence",
                "verbose_name_plural": "Consequences",
            },
        ),
        migrations.AlterModelOptions(
            name="localparticipation",
            options={
                "verbose_name": "participation",
                "verbose_name_plural": "participations",
            },
        ),
        migrations.AlterModelOptions(
            name="placeholderparticipation",
            options={
                "verbose_name": "placeholder participation",
                "verbose_name_plural": "placeholder participations",
            },
        ),
        migrations.AlterModelOptions(
            name="qualificationcategory",
            options={
                "verbose_name": "qualification category",
                "verbose_name_plural": "qualification categories",
            },
        ),
        migrations.AlterModelOptions(
            name="qualificationgrant",
            options={
                "verbose_name": "Qualification grant",
                "verbose_name_plural": "Qualification grants",
            },
        ),
        migrations.AlterModelOptions(
            name="workinghours",
            options={
                "verbose_name": "Working hours",
                "verbose_name_plural": "Working hours",
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="failed",
            field=models.BooleanField(default=False, verbose_name="failed"),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
