# Generated by Django 4.2.4 on 2023-09-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_qualificationcategory_show_with_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="language",
            field=models.CharField(
                choices=[("de", "German"), ("en", "English")],
                default="de",
                max_length=10,
                verbose_name="language",
            ),
        ),
        migrations.AlterField(
            model_name="qualificationcategory",
            name="show_with_user",
            field=models.BooleanField(
                default=True,
                verbose_name="Show qualifications of this category everywhere a user is presented",
            ),
        ),
    ]
