# Generated by Django 4.2.4 on 2023-10-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_ephiosoidcclient"),
    ]

    operations = [
        migrations.AddField(
            model_name="ephiosoidcclient",
            name="logout_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
