# Generated by Django 4.2.6 on 2023-10-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_remove_userprofile_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="identityprovider",
            name="create_missing_groups",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, groups from the claim defined above that do not exist yet will be created automatically.",
                verbose_name="create missing groups",
            ),
        ),
        migrations.AddField(
            model_name="identityprovider",
            name="group_claim",
            field=models.CharField(
                blank=True,
                help_text="The name of the claim that contains the user's groups. Leave empty if your provider does not support this. You can use dot notation to access nested claims.",
                max_length=254,
                null=True,
                verbose_name="group claim",
            ),
        ),
    ]
