# Generated by Django 4.2.6 on 2023-11-28 22:10

from django.db import migrations, models

import ephios.extra.json


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_identityprovider_create_missing_groups_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="failed",
        ),
        migrations.AddField(
            model_name="notification",
            name="processed_by",
            field=models.JSONField(
                blank=True,
                decoder=ephios.extra.json.CustomJSONDecoder,
                default=list,
                encoder=ephios.extra.json.CustomJSONEncoder,
                help_text="List of slugs of notification backends that have processed this notification",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="processing_completed",
            field=models.BooleanField(
                default=False,
                verbose_name="processing completed",
                help_text="All enabled notification backends have processed this notification when flag is set",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="read",
            field=models.BooleanField(default=False, verbose_name="read"),
        ),
    ]
