# Generated by Django 4.2.7 on 2024-01-06 13:21

from django.db import migrations, models
from dynamic_preferences.users.models import UserPreferenceModel

import ephios.extra.json
from ephios.core.services.notifications.backends import enabled_notification_backends
from ephios.core.services.notifications.types import notification_type_from_slug


def migrate_disabled_notifications(apps, schema_editor):
    UserProfile = apps.get_model("core", "UserProfile")
    db_alias = schema_editor.connection.alias
    backends = [backend.slug for backend in enabled_notification_backends()]
    for profile in UserProfile.all_objects.using(db_alias).all():
        try:
            preferences = (
                UserPreferenceModel.objects.using(db_alias)
                .get(section="notifications", name="notifications", instance__pk=profile.pk)
                .value
            )
        except (UserPreferenceModel.DoesNotExist, ValueError):
            continue
        for notification_type, active_backends in preferences.items():
            for backend in set(backends) - set(active_backends):
                profile.disabled_notifications.append([backend, notification_type])
        profile.save()


def revert_disabled_notifications(apps, schema_editor):
    UserProfile = apps.get_model("core", "UserProfile")
    db_alias = schema_editor.connection.alias
    backends = [backend.slug for backend in enabled_notification_backends()]
    for profile in UserProfile.all_objects.using(db_alias).all():
        try:
            preferences_instance = UserPreferenceModel.objects.using(db_alias).get(
                section="notifications", name="notifications", instance__pk=profile.pk
            )
            preferences = preferences_instance.value
            for disabled_tuple in profile.disabled_notifications:
                backend_slug, type_slug = disabled_tuple
                try:
                    notification_type = notification_type_from_slug(type_slug)
                except ValueError:
                    continue
                enabled = preferences.get(type_slug, backends)
                if backend_slug in enabled:
                    enabled.remove(backend_slug)
                preferences[type_slug] = enabled
            preferences_instance.value = preferences
            preferences_instance.save()
        except UserPreferenceModel.DoesNotExist:
            continue


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_remove_notification_failed_notification_processed_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="disabled_notifications",
            field=models.JSONField(
                decoder=ephios.extra.json.CustomJSONDecoder,
                default=list,
                encoder=ephios.extra.json.CustomJSONEncoder,
            ),
        ),
        migrations.RunPython(migrate_disabled_notifications, revert_disabled_notifications),
        migrations.AddField(
            model_name="userprofile",
            name="email_invalid",
            field=models.BooleanField(default=False, verbose_name="Email address invalid"),
        ),
    ]
