# Generated by Django 5.0.1 on 2024-02-09 14:46
import uuid

from django.db import migrations, models

import ephios.extra.json
from ephios.core.signup.flow.builtin.coupled import CoupledSignupFlow
from ephios.core.signup.flow.builtin.manual import ManualSignupFlow
from ephios.core.signup.flow.builtin.participant import (
    InstantConfirmSignupFlow,
    RequestConfirmSignupFlow,
)
from ephios.plugins.baseshiftstructures.structure.named_teams import NamedTeamsShiftStructure
from ephios.plugins.baseshiftstructures.structure.uniform import UniformShiftStructure

METHOD_TO_FLOW_AND_STRUCTURE = {
    "instant_confirmation": (InstantConfirmSignupFlow.slug, UniformShiftStructure.slug),
    "request_confirm": (RequestConfirmSignupFlow.slug, UniformShiftStructure.slug),
    "section_based": (RequestConfirmSignupFlow.slug, NamedTeamsShiftStructure.slug),
    "coupled": (CoupledSignupFlow.slug, UniformShiftStructure.slug),
    "no_selfservice": (ManualSignupFlow.slug, UniformShiftStructure.slug),
}


def copy_structure_configuration_to_signup_flow_configuration(apps, schema_editor):
    Shift = apps.get_model("core", "Shift")
    AbstractParticipation = apps.get_model("core", "AbstractParticipation")

    for p in AbstractParticipation.objects.all():
        preferred = p.structure_data.get("preferred_section_uuid")
        dispatched = p.structure_data.get("dispatched_section_uuid")
        if preferred:
            p.structure_data["preferred_team_uuid"] = preferred
        if dispatched:
            p.structure_data["dispatched_team_uuid"] = dispatched
        p.save()

    for shift in Shift.objects.all():
        shift.signup_flow_configuration = shift.structure_configuration
        try:
            flow_slug, structure_slug = METHOD_TO_FLOW_AND_STRUCTURE[shift.signup_method_slug]
        except KeyError:
            flow_slug = "unknown-after-migration"
            structure_slug = "unknown-after-migration"
        shift.signup_flow_slug = flow_slug
        shift.structure_slug = structure_slug

        # special cases
        if shift.signup_method_slug == "section_based":
            # rename sections to teams and qualification key etc.
            sections_config = shift.structure_configuration
            teams = []
            for section in sections_config.get("sections", []):
                qualification = None
                if section_qualifications := section.get("qualifications", []):
                    qualification = section_qualifications[0]
                teams.append(
                    {
                        "title": section.get("title", ""),
                        "uuid": section.get("uuid", uuid.uuid4()),
                        "qualification": qualification,
                    }
                )

            teams_config = {
                "choose_preferred_team": sections_config.get("choose_preferred_section", False),
                "teams": teams,
            }
            shift.structure_configuration = teams_config

        shift.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_userprofile_disabled_notifications_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="abstractparticipation",
            old_name="data",
            new_name="structure_data",
        ),
        migrations.AddField(
            model_name="shift",
            name="signup_flow_slug",
            field=models.SlugField(default="fallback", verbose_name="signup flow"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shift",
            name="structure_slug",
            field=models.SlugField(default="fallback", verbose_name="structure"),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name="shift",
            old_name="signup_configuration",
            new_name="structure_configuration",
        ),
        migrations.AddField(
            model_name="shift",
            name="signup_flow_configuration",
            field=models.JSONField(
                decoder=ephios.extra.json.CustomJSONDecoder,
                default=dict,
                encoder=ephios.extra.json.CustomJSONEncoder,
            ),
        ),
        migrations.RunPython(
            copy_structure_configuration_to_signup_flow_configuration, migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="shift",
            name="signup_method_slug",
        ),
    ]
