# Generated by Django 5.0.1 on 2024-02-09 14:46

from django.db import migrations, models

import ephios.extra.json


def copy_structure_configuration_to_signup_flow_configuration(apps, schema_editor):
    Shift = apps.get_model("core", "Shift")
    for shift in Shift.objects.all():
        shift.signup_flow_configuration = shift.structure_configuration
        shift.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_userprofile_disabled_notifications_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="abstractparticipation",
            old_name="data",
            new_name="structure_data",
        ),
        migrations.RenameField(
            model_name="shift",
            old_name="signup_configuration",
            new_name="structure_configuration",
        ),
        migrations.RemoveField(
            model_name="shift",
            name="signup_method_slug",
        ),
        migrations.AddField(
            model_name="shift",
            name="signup_flow_configuration",
            field=models.JSONField(
                decoder=ephios.extra.json.CustomJSONDecoder,
                default=dict,
                encoder=ephios.extra.json.CustomJSONEncoder,
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="signup_flow_slug",
            field=models.SlugField(default="fallback", verbose_name="signup flow"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shift",
            name="structure_slug",
            field=models.SlugField(default="fallback", verbose_name="structure"),
            preserve_default=False,
        ),
        migrations.RunPython(
            copy_structure_configuration_to_signup_flow_configuration, migrations.RunPython.noop
        ),
    ]
