# Generated by Django 5.0.3 on 2024-03-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_rename_signup_configuration_shift_structure_configuration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abstractparticipation",
            name="structure_data",
            field=models.JSONField(
                default=dict,
                verbose_name="Data on where this participation lives in the shift structure",
            ),
        ),
    ]
