# Generated by Django 5.0.9 on 2025-01-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_participationcomment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="abstractparticipation",
            name="comment",
        ),
    ]
