# Generated by Django 5.0.14 on 2025-05-31 16:37

from django.db import migrations, models

import ephios.extra.json


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_participationcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="abstractparticipation",
            name="questionnaire_answers",
            field=models.JSONField(default=dict, verbose_name="Answers to questionnaire"),
        ),
        migrations.AddField(
            model_name="shift",
            name="questionnaire",
            field=models.JSONField(
                decoder=ephios.extra.json.CustomJSONDecoder,
                default=list,
                encoder=ephios.extra.json.CustomJSONEncoder,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="saved_questionnaire_answers",
            field=models.JSONField(default=dict, verbose_name="Saved questionnaire answers"),
        ),
    ]
