# Generated by Django 5.0.14 on 2025-05-25 17:35

from django.db import migrations, models

import ephios.extra.json


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_participationcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="questionnaire",
            field=models.JSONField(
                decoder=ephios.extra.json.CustomJSONDecoder,
                default=list,
                encoder=ephios.extra.json.CustomJSONEncoder,
            ),
        ),
    ]
