# Generated by Django 5.2.3 on 2025-07-25 20:47

import django.db.models.deletion
import ephios.extra.json
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0038_eventtype_default_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbstractConsequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.CharField(max_length=255)),
                (
                    "data",
                    models.JSONField(
                        decoder=ephios.extra.json.CustomJSONDecoder,
                        default=dict,
                        encoder=ephios.extra.json.CustomJSONEncoder,
                    ),
                ),
                (
                    "state",
                    models.TextField(
                        choices=[
                            ("needs_confirmation", "needs confirmation"),
                            ("confirmed", "confirmed"),
                            ("executed", "executed"),
                            ("failed", "failed"),
                            ("denied", "denied"),
                        ],
                        default="needs_confirmation",
                        max_length=31,
                        verbose_name="State",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abstract consequence",
                "verbose_name_plural": "Abstract consequences",
                "db_table": "abstractconsequence",
            },
        ),
        migrations.AlterField(
            model_name="shift",
            name="label",
            field=models.CharField(
                blank=True,
                help_text="Optional label to help differentiate multiple shifts in an event.",
                max_length=255,
                verbose_name="label",
            ),
        ),
        migrations.CreateModel(
            name="LocalConsequence",
            fields=[
                (
                    "abstractconsequence_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.abstractconsequence",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affecting_consequences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="affected user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Local consequence",
                "verbose_name_plural": "Local consequences",
                "db_table": "localconsequence",
            },
            bases=("core.abstractconsequence",),
        ),
        migrations.DeleteModel(
            name="Consequence",
        ),
    ]
