# Generated by Django 5.2.6 on 2025-12-04 15:54

from django.db import migrations

import ephios.core.models.users


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_eventtype_default_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualification",
            name="default_expiration_time",
            field=ephios.core.models.users.RelativeTimeModelField(
                blank=True,
                help_text="The default expiration time for this qualification.",
                null=True,
                verbose_name="Default expiration time",
            ),
        ),
    ]
