# Generated by Django 4.1.7 on 2023-05-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesstoken",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="describes manually created tokens",
                verbose_name="Description",
            ),
        ),
    ]
