# Generated by Django 4.1.7 on 2023-05-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_accesstoken_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesstoken",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Describes where and for what this token is used",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="accesstoken",
            name="expires",
            field=models.DateTimeField(null=True),
        ),
    ]
