# Generated by Django 5.0.6 on 2024-07-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_application_post_logout_redirect_uris"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="allowed_origins",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Allowed origins list to enable CORS, space separated",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="hash_client_secret",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="accesstoken",
            name="token",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="post_logout_redirect_uris",
            field=models.TextField(
                blank=True, default="", help_text="Allowed Post Logout URIs list, space separated"
            ),
        ),
    ]
