# Generated by Django 3.0.6 on 2020-06-14 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='service',
            new_name='event',
        ),
    ]
