# Generated by Django 5.2.1 on 2025-05-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("complexsignup", "0002_blockcomposition_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildingblock",
            name="sub_blocks",
            field=models.ManyToManyField(
                through="complexsignup.BlockComposition",
                through_fields=("composite_block", "sub_block"),
                to="complexsignup.buildingblock",
                verbose_name="sub blocks",
            ),
        ),
    ]
