# Generated by Django 5.2.4 on 2025-07-17 10:10
import uuid

from django.db import migrations

from ephios.plugins.complexsignup.structure import ComplexShiftStructure


def adjust_multiblock(apps, schema_editor):
    """
    Change from e.g.
    {"building_block": 8, "choose_preferred_unit": true}
    to
    {"minimum_age": null, "choose_preferred_unit": true, "starting_blocks": [{"building_block": 8, "title": "", "optional": false}]}
    """
    Shift = apps.get_model("core", "Shift")
    for shift in Shift.objects.filter(structure_slug=ComplexShiftStructure.slug):
        old_data = shift.structure_configuration
        if "starting_blocks" in old_data:
            continue  # already converted
        block_pk = old_data["building_block"]
        new_block = {
            "building_block": block_pk,
            "label": "",
            "optional": False,
            "uuid": uuid.uuid4(),
        }
        shift.structure_configuration = {
            "choose_preferred_unit": old_data.get("choose_preferred_unit"),
            "minimum_age": old_data.get("minimum_age"),
            "starting_blocks": [new_block],
        }
        shift.save()
        for participation in shift.participations.all():
            for field_name in ["dispatched_unit_path", "preferred_unit_path"]:
                # adjust dispatched/preferred unit path
                old_path = participation.structure_data.get(field_name)
                if not old_path or len(old_path) < 5:
                    continue
                # we inserted a uuid for having multiple starting blocks in the path and
                # switched to "." as a seperator.
                # What was root-16-18 should now be root.<uuid>.16.18:
                new_path = f"root.{new_block['uuid']}{old_path[4:].replace('-', '.')}"
                participation.structure_data[field_name] = new_path
            participation.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_eventtype_default_description"),
        ("complexsignup", "0003_alter_buildingblock_sub_blocks"),
    ]

    operations = [
        migrations.RunPython(adjust_multiblock),
    ]
