# Generated by Django 4.2.4 on 2023-08-03 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("guests", "0003_auto_20210528_2230"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guestparticipation",
            options={
                "verbose_name": "guest participation",
                "verbose_name_plural": "guest participations",
            },
        ),
        migrations.AlterModelOptions(
            name="guestuser",
            options={
                "verbose_name": "guest user",
                "verbose_name_plural": "guest users",
            },
        ),
    ]
