# Generated by Django 5.2.1 on 2025-05-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_alter_participationcomment_options_and_more"),
        ("guests", "0005_alter_guestuser_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestuser",
            name="qualifications",
            field=models.ManyToManyField(
                blank=True, to="core.qualification", verbose_name="Qualifications"
            ),
        ),
    ]
