# Generated by Django 5.2.6 on 2025-09-11 20:06

from django.db import migrations
from django.db.models import Count

from ephios.core.models.events import PlaceholderParticipation
from ephios.plugins.guests.models import GuestParticipation


def deduplicate_guest_participations(apps, schema_editor):
    GuestUser = apps.get_model("guests", "GuestUser")
    for duplicate_guest in (
        GuestUser.objects.values("email", "event_id").annotate(Count("id")).filter(id__count__gt=1)
    ):
        for participation in GuestParticipation.objects.filter(
            guest_user__email=duplicate_guest["email"],
            guest_user__event_id=duplicate_guest["event_id"],
        ):
            PlaceholderParticipation.objects.create(
                display_name=participation.guest_user.display_name,
                shift=participation.shift,
                state=participation.state,
                structure_data=participation.structure_data,
                finished=participation.finished,
                individual_start_time=participation.individual_start_time,
                individual_end_time=participation.individual_end_time,
            )
            participation.delete()
        GuestUser.objects.filter(
            email=duplicate_guest["email"], event_id=duplicate_guest["event_id"]
        ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_eventtype_default_description"),
        ("guests", "0006_alter_guestuser_qualifications"),
    ]

    operations = [
        migrations.RunPython(deduplicate_guest_participations),
    ]
