# Generated by Django 5.2.6 on 2025-09-11 22:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_eventtype_default_description"),
        ("guests", "0007_alter_guestuser_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="guestuser",
            unique_together={("event", "email")},
        ),
    ]
