# Generated by Django 3.1.2 on 2020-10-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event_management", "0002_auto_20200927_2157"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shift",
            options={
                "ordering": ("meeting_time", "start_time", "id"),
                "verbose_name": "shift",
                "verbose_name_plural": "shifts",
            },
        ),
        migrations.RemoveField(
            model_name="event",
            name="series",
        ),
        migrations.DeleteModel(
            name="EventSeries",
        ),
    ]
