# Generated by Django 3.1.4 on 2021-01-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_management", "0003_auto_20201022_1620"),
    ]

    operations = [
        migrations.AddField(
            model_name="abstractparticipation",
            name="data",
            field=models.JSONField(default=dict),
        ),
    ]
