# Generated by Django 3.1.6 on 2021-02-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_management", "0005_eventtypepreference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abstractparticipation",
            name="state",
            field=models.IntegerField(
                choices=[
                    (0, "requested"),
                    (1, "confirmed"),
                    (2, "declined by user"),
                    (3, "rejected by responsible"),
                    (4, "getting dispatched"),
                ],
                verbose_name="state",
            ),
        ),
    ]
