# Generated by Django 3.1.6 on 2021-02-07 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event_management", "0006_auto_20210204_2257"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="abstractparticipation",
            options={},
        ),
        migrations.AlterModelOptions(
            name="localparticipation",
            options={},
        ),
        migrations.AlterModelTable(
            name="abstractparticipation",
            table="abstractparticipation",
        ),
        migrations.AlterModelTable(
            name="event",
            table="event",
        ),
        migrations.AlterModelTable(
            name="eventtype",
            table="eventtype",
        ),
        migrations.AlterModelTable(
            name="eventtypepreference",
            table="eventtypepreference",
        ),
        migrations.AlterModelTable(
            name="localparticipation",
            table="localparticipation",
        ),
        migrations.AlterModelTable(
            name="shift",
            table="shift",
        ),
    ]
